template_path: vpc/route.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  DestinationCidrBlock: '0.0.0.0/0'
  InternetGatewayId: !stack_output {{ stack_group_config.Environment }}/vpc/gateway/internet.yaml::Id
  RouteTableId: !stack_output {{ stack_group_config.Environment }}/vpc/route-table/public-subnet.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}