template_path: vpc/subnet.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  SubnetName: 'CNet-VPN-NET'
  CidrBlock: 10.12.20.0/24
  AvailabilityZone: {{ stack_group_config.AvailabilityZoneD }}
  VpcId: !stack_output {{ stack_group_config.Environment }}/vpc/vpc.yaml::Id
  RouteTableId: !stack_output {{ stack_group_config.Environment }}/vpc/route-table/private-subnet-c.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}