template_path: vpc/subnetD.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  SubnetName: 'TLSWebApps-CAN-10.12.10.0-PUB'
  CidrBlock: 10.12.10.0/24
  AvailabilityZone: {{ stack_group_config.AvailabilityZoneD }}
  VpcId: !stack_output {{ stack_group_config.Environment }}/vpc/vpc.yaml::Id
  MapPublicIpOnLaunch: "true"
  RouteTableId: !stack_output {{ stack_group_config.Environment }}/vpc/route-table/public-subnet.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}