template_path: vpc/subnet.yaml
parameters:
  Environment: {{ stack_group_config.Environment }}
  SubnetName: 'CNet_ALB_1'
  CidrBlock: 10.12.12.0/24
  AvailabilityZone: {{ stack_group_config.AvailabilityZoneC }}
  VpcId: !stack_output {{ stack_group_config.Environment }}/vpc/vpc.yaml::Id
  RouteTableId: !stack_output {{ stack_group_config.Environment }}/vpc/route-table/public-subnet.yaml::Id
stack_tags:
  "Environment": {{ stack_group_config.Environment }}
  "CreatedBy": {{ stack_group_config.CreatedBy }}
  "Application": {{ stack_group_config.Application }}