AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a network route in route table

Parameters:
  Environment:
    Type: String
  DestinationCidrBlock:
    Type: String
    Default: ""
  InternetGatewayId:
    Type: String
    Default: ""
  NatGatewayId:
    Type: String
    Default: ""
  RouteTableId:
    Type: String
  PeeringConnectionId:
    Type: String
    Default: ""

Conditions:
  IsIpBasedRoute: !Not [!Equals [!Ref DestinationCidrBlock, ""]] 
  IsPublicRoute: !Not [!Equals [!Ref InternetGatewayId, ""]]
  IsPrivateRoute: !Not [!Equals [!Ref NatGatewayId, ""]]
  IsVpcPeeringRoute: !Not [!Equals [!Ref PeeringConnectionId, ""]]

Resources:
  Route:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !If [IsIpBasedRoute, !Ref DestinationCidrBlock, !Ref "AWS::NoValue"]
      GatewayId: !If [IsPublicRoute, !Ref InternetGatewayId, !Ref "AWS::NoValue"]
      NatGatewayId: !If [IsPrivateRoute, !Ref NatGatewayId, !Ref "AWS::NoValue"]
      RouteTableId: !Ref RouteTableId
      VpcPeeringConnectionId: !If [IsVpcPeeringRoute, !Ref PeeringConnectionId, !Ref AWS::NoValue]

